# Generated by Django 4.2.2 on 2023-08-08 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_message"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"ordering": ["created"]},
        ),
    ]
