# Generated by Django 5.0.6 on 2024-05-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='video',
            field=models.CharField(blank=True, default='123', max_length=200, null=True),
        ),
    ]
