# Generated by Django 5.0.6 on 2024-05-23 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_social_discord_project_social_discord_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='social_discord_link',
        ),
        migrations.RemoveField(
            model_name='project',
            name='social_telegram_link',
        ),
        migrations.RemoveField(
            model_name='project',
            name='social_web_link',
        ),
        migrations.RemoveField(
            model_name='project',
            name='social_x_link',
        ),
    ]
