# Generated by Django 5.0.6 on 2024-05-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0013_network"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="networks",
            field=models.ManyToManyField(blank=True, to="projects.network"),
        ),
    ]
