# Generated by Django 5.0.6 on 2024-05-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_project_networks'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
