# Generated by Django 5.0.6 on 2024-05-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_network_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='project_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
