# Generated by Django 5.0.6 on 2024-05-26 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_network_project_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='project_total',
        ),
    ]
