# Generated by Django 5.0.6 on 2024-05-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_remove_network_project_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='archive',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
