# Generated by Django 5.0.6 on 2024-05-27 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_tools'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tools',
            new_name='Tool',
        ),
    ]
